version: "3.8"
networks:
  app-net:

services:
  db:
    image: mysql:8
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    networks:
      - app-net

  nginx:
    image: nginx:stable
    container_name: app_nginx
    depends_on:
      - laravel_php
      - symfony_php
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel:/var/www/laravel:ro
      - ./symfony:/var/www/symfony:ro
    networks:
      - app-net

  laravel_php:
    build:
      context: ./laravel
    container_name: laravel_php
    volumes:
      - ./laravel:/var/www/html
    expose:
      - "9000"
    networks:
      - app-net

  symfony_php:
    build:
      context: ./symfony
    container_name: symfony_php
    volumes:
      - ./symfony:/var/www/html
    expose:
      - "9000"
    networks:
      - app-net
