stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel_test
  DB_USERNAME: root
  DB_PASSWORD: root

services:
  - name: mysql:8.0
    alias: mysql
    command:
      - --default-authentication-plugin=mysql_native_password

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .composer/cache

before_script:
  - apt-get update && apt-get install -y unzip git
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --prefer-dist --optimize-autoloader
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --force

test:
  stage: test
  image: php:8.2-cli
  script:
    - vendor/bin/pest --colors
  only:
    - dev
